// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ClearNodes():Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteNodes(arg1:Array<number>):Promise<Array<model.NodeDTO>>;

export function ExportClashYAML():Promise<string>;

export function ExportNodeLinks():Promise<string>;

export function ExportNodeLinksFiltered(arg1:string):Promise<string>;

export function ExportYAMLFlow():Promise<string>;

export function ExportYAMLFlowFiltered(arg1:string):Promise<string>;

export function GetAvailableProxyTypes():Promise<Array<string>>;

export function GetNodes():Promise<Array<model.NodeDTO>>;

export function GetSettings():Promise<model.TestSettings>;

export function ImportFromFile():Promise<Array<model.NodeDTO>>;

export function ImportFromSubscription(arg1:string):Promise<Array<model.NodeDTO>>;

export function ImportFromText(arg1:string):Promise<Array<model.NodeDTO>>;

export function ImportMultipleFiles():Promise<Array<model.NodeDTO>>;

export function ImportMultipleSubscriptions(arg1:Array<string>):Promise<Array<model.NodeDTO>>;

export function IsRunning():Promise<boolean>;

export function SaveClashYAML():Promise<void>;

export function StartTest():Promise<void>;

export function StopTest():Promise<void>;

export function UpdateSettings(arg1:model.TestSettings):Promise<void>;
