// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearNodes() {
  return window['go']['main']['App']['ClearNodes']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteNodes(arg1) {
  return window['go']['main']['App']['DeleteNodes'](arg1);
}

export function ExportClashYAML() {
  return window['go']['main']['App']['ExportClashYAML']();
}

export function ExportNodeLinks() {
  return window['go']['main']['App']['ExportNodeLinks']();
}

export function ExportNodeLinksFiltered(arg1) {
  return window['go']['main']['App']['ExportNodeLinksFiltered'](arg1);
}

export function ExportYAMLFlow() {
  return window['go']['main']['App']['ExportYAMLFlow']();
}

export function ExportYAMLFlowFiltered(arg1) {
  return window['go']['main']['App']['ExportYAMLFlowFiltered'](arg1);
}

export function GetAvailableProxyTypes() {
  return window['go']['main']['App']['GetAvailableProxyTypes']();
}

export function GetNodes() {
  return window['go']['main']['App']['GetNodes']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportFromFile() {
  return window['go']['main']['App']['ImportFromFile']();
}

export function ImportFromSubscription(arg1) {
  return window['go']['main']['App']['ImportFromSubscription'](arg1);
}

export function ImportFromText(arg1) {
  return window['go']['main']['App']['ImportFromText'](arg1);
}

export function ImportMultipleFiles() {
  return window['go']['main']['App']['ImportMultipleFiles']();
}

export function ImportMultipleSubscriptions(arg1) {
  return window['go']['main']['App']['ImportMultipleSubscriptions'](arg1);
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function SaveClashYAML() {
  return window['go']['main']['App']['SaveClashYAML']();
}

export function StartTest() {
  return window['go']['main']['App']['StartTest']();
}

export function StopTest() {
  return window['go']['main']['App']['StopTest']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
